version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-postgres}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-changeme}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
       - ./db/init_scripts:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    

networks:
  postgres:
    driver: bridge 

volumes:
  postgres: